# Generated by Django 2.2.2 on 2019-06-10 11:01

from django.db import migrations, models
import urlshotener.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshotener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(default=urlshotener.models.generate_url),
        ),
    ]
