# Generated by Django 2.2.2 on 2019-06-10 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlshotener', '0002_auto_20190610_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
