# Generated by Django 2.2.2 on 2019-06-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshotener', '0005_auto_20190610_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
